language: ruby
cache: bundler
rvm:
  - 2.3.1
branches:
  only:
    - master
services:
  - postgresql
before_script:
  - cp config/secrets.yml.travis config/secrets.yml
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bin/rake db:create db:schema:load
